---
Description: >-
  Codebuild project invoked from Codepipeline for an entity.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Microservice name
        Parameter:
          - ApplicationServiceName
      - Label:
          default: Repository Settings
        Parameters:
          - ApplicationServiceName
          - AppDefaultBranch
          - GithubOrganization
      - Label:
          default: Build Compute Settings
        Parameters:
          - BuildComputeConfiguration
          - Environment
      - Label:
          default: Mandatory tags.
        Parameters:
          - CostcentreTag
          - ProjectTag
          - LiveTag
      - Label:
          - default: Environment tags
        Parameters:
          - EnvironmentTag
          - EmailTag
      - Label:
          default: IAM Settings. Defined by CE team.
        Parameters:
          - IamBoundaryPolicy
      - Label:
          default: Storage Settings. Defined by CE team.
    ParameterLabels: []

Parameters:
  NonprodVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Nonprod VPC Id

  NonprodSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Nonprod VPC Subnets to run the test into.

  CodeBuildRoleName:
    Type: String

  BuildComputeConfiguration:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Medium
      - Large

  ApplicationServiceName:
    Type: String

  TestSG:
    Type: String
    AllowedPattern: "sg-[a-z0-9]+"    

  Environment:
    Type: String
    Default: aws/codebuild/standard:4.0
    AllowedValues:
      - aws/codebuild/standard:3.0
      - aws/codebuild/standard:4.0

  BuildSpecFile:
    Type: String
    Default: buildspec.yml

  BuildLogsRetentionDays:
    Type: Number
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 30

  IamBoundaryPolicyName:
    Type: String
    Default: ccoe/js-developer
    AllowedPattern: '[a-zA-Z0-9-\/.]+'

  CostcentreTag:
    AllowedPattern: '[\x20-\x7E]+'
    ConstraintDescription: Must be ASCII
    MaxLength: 128
    MinLength: 2
    Type: String

  ProjectTag:
    AllowedPattern: '[\x20-\x7E]+'
    ConstraintDescription: Must be ASCII
    MaxLength: 128
    MinLength: 2
    Type: String

  EnvironmentTag:
    AllowedPattern: '[\x20-\x7E]+'
    ConstraintDescription: Must be ASCII
    MaxLength: 128
    MinLength: 2
    Type: String
    Default: management

  EmailTag:
    AllowedPattern: '[\x20-\x7E]+'
    ConstraintDescription: Must be ASCII
    MaxLength: 128
    MinLength: 2
    Type: String
    Default: scintsvcs.support@sainsburys.co.uk

  LiveTag:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
    
Mappings:
  CodeBuild:
    EnvironmentSize:
      Small: BUILD_GENERAL1_SMALL
      Medium: BUILD_GENERAL1_MEDIUM
      Large: BUILD_GENERAL1_LARGE

Resources:
  BuildLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'test/pipeline/${ApplicationServiceName}'
      RetentionInDays: !Ref BuildLogsRetentionDays

  ApplicationTesting:
    Type: AWS::CodeBuild::Project
    Properties:
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref BuildLogsGroup
          Status: ENABLED
        S3Logs:
          Location: !Sub
            - '${ArtifactsBucketArn}/${ApplicationServiceName}/tests/logs'
            - ArtifactsBucketArn: !ImportValue "CICD::mgmt::Bucket::Artifacts::Arn"
          Status: ENABLED
      Name: !Sub 'test-${ApplicationServiceName}'
      EncryptionKey: !ImportValue "CICD::mgmt::KMS::Key::Arn"
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${CodeBuildRoleName}'
      Description: !Sub 'Executes tests for ${ApplicationServiceName} in ${AWS::AccountId}'
      Environment:
        ComputeType: !FindInMap [ "CodeBuild", "EnvironmentSize", !Ref BuildComputeConfiguration ]
        Image: !Ref Environment
        Type: LINUX_CONTAINER
        PrivilegedMode: False
        EnvironmentVariables:
          - Name: CFN_TPL_BUCKET
            Type: PLAINTEXT
            Value: !ImportValue "CICD::mgmt::Bucket::CfnTemplates::Name"
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref 'AWS::AccountId'
          - Name: MICROSERVICE_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationServiceName
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref 'BuildSpecFile'     
      Tags:
        - Key: costcentre
          Value: !Ref 'CostcentreTag'
        - Key: environment
          Value: !Ref 'EnvironmentTag'
        - Key: email
          Value: !Ref 'EmailTag'
        - Key: project
          Value: !Ref 'ProjectTag'
        - Key: live
          Value: !Ref 'LiveTag'
      VpcConfig:
        VpcId: !Ref NonprodVpcId
        Subnets: !Ref NonprodSubnets
        SecurityGroupIds:
          - !Ref 'TestSG'

  TestingReportGroup:
    Type: AWS::CodeBuild::ReportGroup
    Properties:
      ExportConfig:
        ExportConfigType: S3
        S3Destination:
          Bucket: !ImportValue "CICD::mgmt::Bucket::Artifacts::Name"
          EncryptionDisabled: False
          EncryptionKey: !ImportValue "CICD::mgmt::KMS::Key::Arn"
          Packaging: NONE
          Path: !Sub 'test/reports/${ApplicationServiceName}/'
      Name: !Sub 'test-${ApplicationServiceName}'
      Tags:
        - Key: costcentre
          Value: !Ref 'CostcentreTag'
        - Key: environment
          Value: !Ref 'EnvironmentTag'
        - Key: email
          Value: !Ref 'EmailTag'
        - Key: project
          Value: !Ref 'ProjectTag'
        - Key: live
          Value: !Ref 'LiveTag'          
      Type: TEST

  ReportSharing:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: False
      Name: !Sub 'shared-${ApplicationTesting}'
      Principals:
        - !ImportValue "CICD::mgmt::Account::Id"
      ResourceArns:
        - !GetAtt 'TestingReportGroup.Arn'
        - !GetAtt 'ApplicationTesting.Arn'
      Tags:
        - Key: costcentre
          Value: !Ref 'CostcentreTag'
        - Key: environment
          Value: !Ref 'EnvironmentTag'
        - Key: email
          Value: !Ref 'EmailTag'
        - Key: project
          Value: !Ref 'ProjectTag'
        - Key: live
          Value: !Ref 'LiveTag'

Outputs:
  TestProjectName:
    Value: !Ref ApplicationTesting
